/* eslint-disable @typescript-eslint/no-explicit-any */
export const SelectStyles = {
  control: (base: any, state: { isFocused: any }) => ({
    ...base,
    fontSize: '1.2rem',
    fontWeight: 700,
    textAlign: 'center',
    color: 'white',
    borderRadius: '999px',
    padding: '6px 5px',
    backgroundColor: '#44475a',
    minWidth: '6rem',
    height: '3rem',
    boxShadow: 'none',
    border: state.isFocused && '1px solid white !important',
    userSelect: 'none',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  }),
  option: (base: any) => ({
    ...base,
    color: 'white',
    fontSize: '1.2rem',
    fontWeight: 700,
    textAlign: 'center',
    userSelect: 'none',
    backgroundColor: '#44475a',
    '&:hover': {
      backgroundColor: '#21274F',
      borderRadius: '1rem',
    },
  }),
  menu: (base: any) => ({
    ...base,
    backgroundColor: '#44475a',
    fontWeight: 700,
    textAlign: 'center',
    fontSize: '1.2rem',
    borderRadius: '1rem',
    border: '1px solid #21274F !important',
    userSelect: 'none',
  }),
  singleValue: (base: any) => ({
    ...base,
    fontWeight: 700,
    textAlign: 'center',
    fontSize: '1.2rem',
    color: 'white',
    userSelect: 'none',
  }),
  menuList: (base: any) => ({
    ...base,
    padding: '0',
    fontWeight: 700,
    textAlign: 'center',
    fontSize: '1.2rem',
    borderRadius: '1rem',
    userSelect: 'none',
  }),
  valueContainer: (base: any) => ({
    ...base,
    fontWeight: 700,
    textAlign: 'center',
    fontSize: '1.2rem',
    borderRadius: '1rem',
    userSelect: 'none',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
  }),
};
